//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by config.rc
//
#define IDD_CONFIGDLG                   101
#define IDD_MACRODLG                    102
#define IDD_STATUS                      103
#define IDD_STATUS_1                    103
#define IDD_STATUS_123                  104
#define IDD_STATUS_2                    105
#define IDD_STATUS_12                   106
#define IDD_STATUS_13                   107
#define IDD_STATUS_3                    108
#define IDD_STATUS_23                   109
#define IDC_COMBOCONT                   1000
#define IDC_BCONFIG                     1001
#define IDC_CHECKACTIVE                 1002
#define IDC_LDEVICES                    1003
#define IDC_B_A                         1004
#define IDC_E_A                         1005
#define IDC_B_B                         1006
#define IDC_E_B                         1007
#define IDC_B_START                     1008
#define IDC_E_START                     1009
#define IDC_B_ZTRIG                     1010
#define IDC_E_ZTRIG                     1011
#define IDC_B_LTRIG                     1012
#define IDC_E_LTRIG                     1013
#define IDC_B_RTRIG                     1014
#define IDC_E_RTRIG                     1015
#define IDC_BAS_UP                      1016
#define IDC_EAS_UP                      1017
#define IDC_BAS_DOWN                    1018
#define IDC_EAS_DOWN                    1019
#define IDC_BAS_LEFT                    1020
#define IDC_EAS_LEFT                    1021
#define IDC_BAS_RIGHT                   1022
#define IDC_EAS_RIGHT                   1023
#define IDC_B_CUP                       1024
#define IDC_E_CUP                       1025
#define IDC_B_CDOWN                     1026
#define IDC_E_CDOWN                     1027
#define IDC_B_CLEFT                     1028
#define IDC_E_CLEFT                     1029
#define IDC_B_CRIGHT                    1030
#define IDC_E_CRIGHT                    1031
#define IDC_B_DPUP                      1032
#define IDC_E_DPUP                      1033
#define IDC_B_DPDOWN                    1034
#define IDC_E_DPDOWN                    1035
#define IDC_B_DPLEFT                    1036
#define IDC_B_M1                        1037
#define IDC_E_DPLEFT                    1038
#define IDC_B_DPRIGHT                   1039
#define IDC_E_DPRIGHT                   1040
#define IDC_SPINMAX                     1041
#define IDC_E_MAX                       1042
#define IDC_SPINMIN                     1043
#define IDC_E_MIN                       1044
#define IDC_B_CLEAR                     1045
#define IDC_B_M2                        1046
#define IDC_E_M1                        1047
#define IDC_E_M2                        1048
#define IDC_E_M1VAL                     1049
#define IDC_E_M2VAL                     1050
#define IDC_SPINM1                      1051
#define IDC_SPINM2                      1052
#define IDC_CHECKRUMBLE                 1053
#define IDC_CHECKMEMPAK                 1053
#define IDC_B_APPLY                     1054
#define IDC_B_MAC1                      1055
#define IDC_B_MAC2                      1056
#define IDC_E_MAC1                      1057
#define IDC_E_MAC2                      1058
#define IDC_BTOG_MAC1                   1059
#define IDC_BTOG_MAC2                   1060
#define IDC_CHECK_MAC_A                 1061
#define IDC_B_MAC_CLEAR                 1062
#define IDC_BSAVE                       1063
#define IDC_BLOAD                       1064
#define IDC_CHECK_MAC_B                 1065
#define IDC_CHECK_MAC_S                 1066
#define IDC_B_MAC3                      1066
#define IDC_CHECK_MAC_Z                 1067
#define IDC_EDITX                       1067
#define IDC_E_MAC3                      1067
#define IDC_CHECK_MAC_TL                1068
#define IDC_EDITY                       1068
#define IDC_BTOG_MAC3                   1068
#define IDC_CHECK_MAC_TR                1069
#define IDC_STICKPIC                    1069
#define IDC_B_MAC4                      1069
#define IDC_CHECK_MAC_AU                1070
#define IDC_XREL                        1070
#define IDC_E_MAC4                      1070
#define IDC_CHECK_MAC_AD                1071
#define IDC_XABS                        1071
#define IDC_BTOG_MAC4                   1071
#define IDC_CHECK_MAC_AL                1072
#define IDC_XRAD                        1072
#define IDC_B_MAC5                      1072
#define IDC_CHECK_MAC_AR                1073
#define IDC_YREL                        1073
#define IDC_E_MAC5                      1073
#define IDC_CHECK_MAC_CU                1074
#define IDC_RADIO3                      1074
#define IDC_YABS                        1074
#define IDC_BTOG_MAC5                   1074
#define IDC_CHECK_MAC_CD                1075
#define IDC_STATICX                     1075
#define IDC_CHECK_MAC_CL                1076
#define IDC_STATICY                     1076
#define IDC_CHECK_MAC_CR                1077
#define IDC_XSEM                        1077
#define IDC_CHECK_MAC_DU                1078
#define IDC_YSEM                        1078
#define IDC_CHECK_MAC_DD                1079
#define IDC_SPINX                       1079
#define IDC_CHECK_MAC_DL                1080
#define IDC_SPINY                       1080
#define IDC_CHECK_MAC_DR                1081
#define IDC_ANALOGSTICKLABEL            1082
#define IDC_MOREBUTTON1                 1083
#define IDC_MOREBUTTON2                 1085
#define IDC_CHECK_B                     1086
#define IDC_CHECK_A                     1087
#define IDC_CHECK_R                     1088
#define IDC_CHECK_Z                     1089
#define IDC_CHECK_L                     1090
#define IDC_CHECK_CUP                   1091
#define IDC_CHECK_CLEFT                 1092
#define IDC_CHECK_CRIGHT                1093
#define IDC_CHECK_CDOWN                 1094
#define IDC_MOREBUTTON3                 1098
#define IDC_CHECK_DUP                   1100
#define IDC_CHECK_DLEFT                 1101
#define IDC_CHECK_DRIGHT                1102
#define IDC_CHECK_DDOWN                 1103
#define IDC_CHECK_START                 1104
#define IDC_MOREBUTTON0                 1105
#define IDC_MOREBUTTON4                 1106
#define IDC_BUTTONSLABEL                1107
#define IDC_COMBOLABEL                  1108
#define IDC_MACROBOX                    1109
#define IDC_MACROLIST                   1111
#define IDC_BUTTON1                     1112
#define IDC_BUTTON2                     1113
#define IDC_MOREBUTTON5                 1114
#define IDC_BUTTON3                     1115
#define IDC_BUTTON4                     1116
#define IDC_CHECK_PLAYCOMBO             1116
#define IDC_BUTTON5                     1117
#define IDC_MACROCOMBOBOX               1117
#define IDC_BUTTON6                     1118
#define IDC_RADIO1                      1118
#define IDC_BUTTON7                     1119
#define IDC_RADIO2                      1119
#define IDC_RADIO4                      1120
#define IDC_CLEARBUTTONS                1122
#define IDC_MOREBUTTON6                 1124
#define IDC_CHECK1                      1125
#define IDC_CHECK_ANGDISP               1125
#define IDC_SLIDERX                     1126
#define IDC_SLIDERY                     1127

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1128
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
